### ISSUE TITLE
[Mobile Bug] Custom Background issue

### ISSUE THREAD

**Issue by Mr-Tomato123** [ArtexJay/Obsidian-CyberGlow#44]
**Describe the bug**
When setting a Custom Background (both on mobile and on IPad) the Blur, Brightness and Saturation settings do not work.

**To Reproduce**
1. Style settings
2. Select the Obsidian Community background 
3. Try to use the settings (the Opacity setting does work)

**Screenshots, Gifs, Video**
 The background at min blur, brightness and saturation
![IMG_0070](https://user-images.githubusercontent.com/121110164/218050365-c10a0ccf-a580-4629-9ea1-c250589761a8.png)

The background at max blur, brightness and saturation
![IMG_0072](https://user-images.githubusercontent.com/121110164/218049854-fc4e061e-11f9-4ebe-9641-38b4b27f9f9b.png)

**Mobile :**
 - OS: both IPadOS and Android 
 - Device: both IPad 9 and Huawei p20
 - Obsidian Version v1.4.1
 - CyberGlow Version v7.8.0

**Additional context**
Additionally, the preset’s for the background cut off automatically for the screen size with no control.

**Comment by ArtexJay** [comment]
I've noticed this happen to it seems that to fix this try resetting Saturation, it should immediately fix itself afterwards.
I think this might be a glitch due to the inclusion of Saturation.
Or to be safe reset all 3 of them with opacity.

I will try to check what's causing it to happen.

**Comment by ArtexJay** [comment]
> the preset’s for the background cut off automatically for the screen size with no control.

Can you show this?

**Comment by Mr-Tomato123** [comment]
> Can you show this?

Yes, if you look at the display on the images of the original post you can see the background is half (roughly) of the original/the one displayed on pc

Aka this one
![Obsidian-Community.png](https://user-images.githubusercontent.com/121110164/219303392-3a043b84-9009-4387-a709-bad57f92e0db.png)

 On mobile its even more cut off and looks like this
![Screenshot_20230216_100043_md.obsidian.jpg](https://user-images.githubusercontent.com/121110164/219303811-d14dd0a3-efa8-444a-95ee-5e103e5906cf.jpg)

**Comment by ArtexJay** [comment]
Huh, that's really weird.

When something like this happened to me usually on first theme install of this new update, you'd have to try resetting the all four of them then it should automatically adjust itself.

I will be look into this for sure. maybe remove saturation as I noticed this only when i added saturation.

**Comment by ArtexJay** [comment]
As for the image cropping, I have not changed the behavior of how Style Settings crop or fits background images for the screen.
For mobile what kind of change do you want see happen? 
Please open another issue for the image cropping so these two things don't get mixed up here.

**Comment by ArtexJay** [comment]
New Update push that should resolve the issue, please update the theme (check if there are any updates for Style settings too) and let me know if my changes resolved the primary issue.

**Comment by Mr-Tomato123** [comment]
I have updated the theme and style settings.

The updates did not seem to change the problem. 
The "Saturation", "Brightness" and "Blur" options still do not have any effect.

It would seem that they do not apply at all to the background (if they would have simply been stuck on the default setting there would be a level of blur/brightness that matches the default, however, it seems that both of those [and saturation though it is less clear] are not present at all).

**Comment by ArtexJay** [comment]
weird, I am completely unable to replicate this then.
Opacity, Saturation, Brightness and Blur works/are able to be changed on my devices: tablet, phone, computer. 
So I'm not sure how you're having this issue of them not working at all.

**Comment by Mr-Tomato123** [comment]
at this point i am very confused. everything works great everywhere i check it **except** on my ipad. i think this issue is solved and it is just something on my end that is acting wierd D:
